server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-north-1.pooler.supabase.com:6543/postgres
    username: postgres.iatcnetlfbiijmjmqikv
    password: Mora@2004
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false

jwt:
  secret: "thisisaverylongandcomplexsecretkeythatshouldnotbeemptyornullforenhancedsecurity"
  expiration: 3600000 # 1 hour

file:
  upload-dir: /tmp/uploads